### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by nihui** [nihui/opencv-mobile#2]
- [x] fix android cmake link libz
- [x] strip opencv2 libopencv_info
- [x] package ios fat library
- [x] ios bitcode
- [x] create release
